### ISSUE TITLE
True Tiles - settings tab following mouse cursor

### ISSUE THREAD

**Issue by SCESW** [aki-art/ONI-Mods#12]
True Tiles - Clicked MODS from ONI start screen Options menu and scrolled down to True Tiles, Settings.
Clicked on the 'Open Folder' on the 'Alt Airflow' tab and after I closed the folder winder, the 'Alt Airflow' button was attached to my mouse cursor.
I was able to Quit the game and reload, so not an immediate crash bug, but should be looked into just in case.
Thanks for a great mod!

**Comment by aki-art** [comment]
Issue with the UI library im using, unfortunately out of my scope to fix. Pressing an esc key might solve this the next time.
Did not get any further reports either so seems like a very rare bug too.
Sorry for the inconvenience.
