### ISSUE TITLE
Update from 05.10 crashes my game (StainedGlassTile)

### ISSUE THREAD

**Issue by michaelvolz** [aki-art/ONI-Mods#15]
please remove

**Comment by aki-art** [comment]
Should be fixed already in version 1.2.4
Use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to force update my mod please, Steam struggled to update mods sometimes without this. 

If you are still crashing, then please send me the log of the game:
**Windows:** 
`C:\Users\%username%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log`
  **Mac: 
`~/Library**/Logs/Klei/Oxygen Not Included/Player.log`
 **Linux:** 
`~/.config/unity3d/Klei/Oxygen Not Included/Player.log`
