### ISSUE TITLE
Isn't gas proof (as "stated" in description)

### ISSUE THREAD

**Issue by soerenkk** [aki-art/ONI-Mods#2]
As the first thing, I've decided to test it out.

Notice the tool tip of the Plastic Curtain:

![tooltip](https://user-images.githubusercontent.com/4021353/89193107-c8003b80-d5a5-11ea-846b-b904e7467bc5.png)

It says: "... prevents gases from seeping into the colony...", which means it shouldn't pass gas when dupes walk through it (even though that doesn't follow real life physics).

So I set up this test where I made a vacuum between 2 plastic curtains:

![before](https://user-images.githubusercontent.com/4021353/89193934-f7637800-d5a6-11ea-9d12-34d7d858f32e.png)

Then I asked my dupe Rowan to get to the left side, and then he automaticly went back to do other chores, and this happend:

![after](https://user-images.githubusercontent.com/4021353/89193994-119d5600-d5a7-11ea-8369-2ab1f49147cc.png)

The vacuum had then gotten some oxygen in that replaced the vacuum. Also it seems that gas only enters when going from the left to the right.

**Comment by aki-art** [comment]
This is it's intended behaviour. Notice that Manual airlocks and Mehcanical airlocks have the same description, they too also allow gas through when they are open.
The gas will also tend to flow from higher pressure area to lower pressure, and often favors one direction over the other.
