### ISSUE TITLE
[Bio Inks] Crafting Station Allows slime to offgas, leading to near-infinite chore

### ISSUE THREAD

**Issue by Lbphero** [aki-art/ONI-Mods#20]
I don't know if this is the correct place to describe this, but I wanted to make you aware that the Suspicious bio-ink requires slime, which can offgas, which leads to it losing mass inside the crafting station constantly under usual oxygen conditions.  

Up to you if you wanna do anything about it, but I find containing the crafting station inside a liquid to be aesthetically displeasing.

**Comment by aki-art** [comment]
Fixed in the next version, going live tomorrow, (after Hot Shots is released)
