### ISSUE TITLE
Incorrect text display for equipment

### ISSUE THREAD

**Issue by cwt9527** [aki-art/ONI-Mods#21]
Incorrect text display for equipment~It seems to show a problem, as in the picture!
![1](https://user-images.githubusercontent.com/115734919/199310741-88179785-be28-46ff-9258-fe9b2a87c2b3.PNG)
![2](https://user-images.githubusercontent.com/115734919/199310746-af0df5b0-a0d3-4b3d-9c00-5a8bc294fb02.PNG)

**Comment by aki-art** [comment]
Fixed in 1.3, going live later today
