### ISSUE TITLE
Crash with new update Hot Shots

### ISSUE THREAD

**Issue by Jheavi** [aki-art/ONI-Mods#23]
Crash when trying to load game, game says this mod is probably the causant.
[Player.log](https://github.com/aki-art/ONI-Mods/files/10245706/Player.log)

**Comment by aki-art** [comment]
it appears you have a very outdated version of my mod.
please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283), and make sure True Tiles is v1.2
