### ISSUE TITLE
"More Small Sculptures" overrides pokeshell spawn graphics

### ISSUE THREAD

**Issue by Mr-Beard** [aki-art/ONI-Mods#25]
I've noticed since the latest update to "More Small Sculptures" that pokeshell spawns have been affected. In the Printing Pod, their graphic shows up as the statue from this mod; in-game, pokeshell spawns are completely invisible.

No other mods were activated at the time when I discovered this bug.

![2022-12-18 00_54_42-Oxygen Not Included](https://user-images.githubusercontent.com/7281829/208285702-705fa9bd-456a-4551-91d4-2be4a27c7897.png)

**Comment by aki-art** [comment]
oh, sorry. 
i accidentally named my animation the same name. fix soon.

**Comment by aki-art** [comment]
Fixed in v1.2.1
If it's still an issue please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283)
