### ISSUE TITLE
[Plastic Door] [Crash] Dupe forcibly moved past Atmo Checkpoint into Curtain immediately crashes

### ISSUE THREAD

**Issue by SuperCorgi** [aki-art/ONI-Mods#3]
### Output Log
[output_log_PlasticDoor.txt](https://github.com/aki-art/ONI-Mods/files/5109329/output_log_PlasticDoor.txt)

### Mods Enabled
Plastic Door

### Version
Using the Mod Updater, verified that the mod is currently up to date.
![image](https://user-images.githubusercontent.com/54047565/90900512-8b9b5080-e397-11ea-83df-79008f0f77ae.png)

### Steps to Reproduce
Create a row of tiles, and on the farthest right tile, place a Plastic Door. To the left of the door, place an Atmo Suit Checkpoint facing towards the plastic door. To the left of the checkpoint, place at least one Atmo Suit Dock. The Atmo Suit Checkpoint should have no suits attached, so no dupes should pass from left to right.
![image](https://user-images.githubusercontent.com/54047565/90898979-3eb67a80-e395-11ea-9d51-1ce103c7116e.png)

Queue tile replacements (for example, replace with plastic tiles) for the three rightmost tiles. 
![image](https://user-images.githubusercontent.com/54047565/90899900-9ef9ec00-e396-11ea-8c95-880fda445894.png)

Have three dupes working on the tiles at the same time. The dupe working on the rightmost tile must be standing **on the same tile as the checkpoint.** **Ensure that the dupe working on the middle replacement finishes first.** 
![image](https://user-images.githubusercontent.com/54047565/90899469-f5b2f600-e395-11ea-94ea-cd8216e9c6f8.png)

When the middle tile finishes, the dupe working on the right tile will transition past the Atmo Suit Checkpoint and into the Plastic Door, since the dupe believes he is in danger of falling for a split second. Immediately after, the game will crash.

### Notes
It has failed to reproduce a couple times in my attempts. Both times I believe was because I set speed to x1 (instead of x3) and paused the game just before/just as the middle tile finished construction. It may be even more reproducible by simply deconstructing the tile the rightmost dupe is on. It appears that in the instant Curtain is attempting to get the next transition location from the Navigator, the game has not yet recalculated the transition path, since the dupe was forced to pass the atmo checkpoint.

**Comment by aki-art** [comment]
Fixed in v1.3
