### ISSUE TITLE
CTD on Colony Start with True Tiles installed

### ISSUE THREAD

**Issue by WafflyNimb** [aki-art/ONI-Mods#35]
[Player.log](https://github.com/aki-art/ONI-Mods/files/10529875/Player.log)

Hey there, 
I'm dying to try out your mod since it looks really spiffy! Unfortunately the game crashed to desktop whenever i try to load a save or start a new colony. 

I don't think my other mods are the problem, since the game runs rather smootly with all of them installed. 

If you could take a look at the matter I would be very pleased. Attached is my latest player.log after the game crashed with "True Tiles" enabled.

Thanks a lot!

**Comment by aki-art** [comment]
You have an outdated version of my mod. Please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283)
