### ISSUE TITLE
Bio-Inks Mod: Crash on click of Exosuit Crafting Station [Details Inside]

### ISSUE THREAD

**Issue by Dimitry-Blitzbrieg** [aki-art/ONI-Mods#39]
I've seen on Steam a Discussion related to this problem, Though I'm Going to describe what happened. I saw your mod and decided to install it and use it on an already existing save. [OneDrive Link will give access to Save files copied from Main save folder] Everything has been going fine until I clicked on The Exosuit Forge. then....Crash screen... This has been Repeated 3 times showing that the interaction with the Exosuit Forge Indeed is the Cause of the Crash. Strangely though The crash screen didn't show any of the mods Being disabled Including Bio-Ink. Here Are links to the Log files The Copypaste Of what showed up on the crash screen and The World Save Files. Hope this is enough information to assist you in Finding the fault and making a possible Correction. if you need anything else let me know!

World save files: https://1drv.ms/u/s!Am8EqDAELkGYgbQSMitFTM4WcnMXNA?e=DkMzpq  (Note: All this is in View Only mode to prevent Bad actors from coming in and modifying the files. I'm hoping you are able to download the files with no problems. but if any arise i will give you the link to modify upon your request, but i'll dm it to you.

Crash Screen Paste: https://pastebin.com/17Cw3t2P

Player-Prev Log: https://pastebin.com/rf80vDGw

Player Log: https://pastebin.com/gnZ27q9t

**Comment by aki-art** [comment]
Fixed in v1.2.9.2, live on workshop. Please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to make sure it's the correct version.
