### ISSUE TITLE
Decor pack I - Crash

### ISSUE THREAD

**Issue by Marcoags** [aki-art/ONI-Mods#43]
Game crashing when deconstructing carpet tiles, landscape canvas (the large horizontal one) and portrait canvas (the large vertical one). Does not crash when deconstructing black canvas (the small one). In crash screen, to "help resolve the issue" game auto unchecks this mod and [Vanilla+DLC] Deconstructable POI props. Game still crashes in the same save when mods are not loaded.

Problem mod:
- Decor Pack I

**Log**

[Player.log](https://github.com/aki-art/ONI-Mods/files/11098752/Player.log)

**OS**
Windows 10 Pro

**Additional context**

**Comment by aki-art** [comment]
This error seems to come from Deconstrucable POI Props, and Decor Pack falsely blamed by the game. I do not touch carpet tiles in any way. That mod modifies all deconstructions and reapplies the "category" of fiber as a dropped item, crashing the game since that is not an item.

**Comment by Marcoags** [comment]
Got it. Thanks for your time!
________________________________
De: Aki ***@***.***>
Enviado: jueves, 30 de marzo de 2023 3:26
Para: aki-art/ONI-Mods ***@***.***>
Cc: Marcoags ***@***.***>; Author ***@***.***>
Asunto: Re: [aki-art/ONI-Mods] Decor pack I - Crash (Issue #43)


This error seems to come from Deconstrucable POI Props, and Decor Pack falsely blamed by the game. I do not touch carpet tiles in any way. That mod modifies all deconstructions and reapplies the "category" of fiber as a dropped item, crashing the game since that is not an item.
