### ISSUE TITLE
Old Savegame with Decor Pack I Statues crashes on load

### ISSUE THREAD

**Issue by Sgt-Imalas** [aki-art/ONI-Mods#45]
**Describe the bug**
Loading the attached savegame crashes.
This happens both with decor pack I active and indactive

**Problem mod**  
Decor Pack I

**To Reproduce**
1. Start Game
2. Load colony -> [AllRocketsBlownUp.zip](https://github.com/aki-art/ONI-Mods/files/11130949/AllRocketsBlownUp.zip)
3. Crash on load

**Expected behavior**
Savegame loads

**Log**
[Player.log](https://github.com/aki-art/ONI-Mods/files/11130946/Player.log)

**OS**
[Windows]

**Comment by aki-art** [comment]
This is a crash about More Marble Sculptures, you have to have it enabled to load the sculptures.
