### ISSUE TITLE
Backwalls: Error msg on load

### ISSUE THREAD

**Issue by wilki24** [aki-art/ONI-Mods#50]
**Describe the bug**
Error msg:
The script 'Backwalls.Cmps.DefaultSetter' could not be instantiated!

**Problem mod**  
Backwalls

**To Reproduce**
1. Start Game...

**Expected behavior**
No errors on load.

**Log**
[Player.log](https://github.com/aki-art/ONI-Mods/files/11943203/Player.log)

**OS**
Windows

**Additional context**
I did add backwalls to an existing save, also I'm running a lot of mods. Backwalls seems to work okay.

**Comment by aki-art** [comment]
Can you confirm if your game crashes without backwalls installed?
That "error" is just a warning, it should not result in a crash. 
Your game appears to be forcibly shut down.

**Comment by aki-art** [comment]
Also, can you please send another log with Debug Console disabled? That mod is interfering with the log output.

**Comment by wilki24** [comment]
Ok, I disabled the debug console mod, and this time let the game load my save, run for a short while, and then quit. That error message is spammed many times while the save loads, I suspect once for each tile I've placed?

[Player.log](https://github.com/aki-art/ONI-Mods/files/11962861/Player.log)

**Comment by aki-art** [comment]
There is no error message in this log.
The DefaultSetter thing is just a warning and causes no crash, which is why i asked for the full log. I accidentally left it in, it will be gone in the next update. 
Whatever actually crashed was hidden by Debug Console, and is unlikely to be related to my mod.
