### ISSUE TITLE
True Tiles Error on Save Load

### ISSUE THREAD

**Issue by Mazinem95** [aki-art/ONI-Mods#51]
**Describe the bug**
Crash on colony/save load both old and new when trying to use True Tiles mod. I had been using it previously earlier in 2023 then took a break from the game for a while. Recently, last couple of weeks, got back into the game and noticed the mod had been turned off. When turning back on and attempting to load a colony, the game crashes siting True Tiles as the issue. The problem persists with both new games and current games/saves.

**Problem mod**  
- True Tiles

**To Reproduce**
1. Start Game...
2. Load or start new colony...
3. Crash...

**Expected behavior**
Expected game to work as previous times when using the True Tiles mod

**Log**
[Error Message.txt](https://github.com/aki-art/ONI-Mods/files/11951190/Error.Message.txt)
[Mazinem ONI Log File.txt](https://github.com/aki-art/ONI-Mods/files/11951191/Mazinem.ONI.Log.File.txt)

**OS**
Windows

**Additional context**

**Comment by aki-art** [comment]
Outdated mod, please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283)
