### ISSUE TITLE
Backwalls translation

### ISSUE THREAD

**Issue by DarkEviL88** [aki-art/ONI-Mods#54]
I translated your mod into Russian, but part of the mod is not translated at all, such as settings, in the .po file seems to have lines from the settings, but in the game they are still in English. Also the description of the decorative backwall is not translated.
![image](https://github.com/aki-art/ONI-Mods/assets/50534207/119dabad-d6cd-4a22-9417-b19126b53b60)

Also, part of the translation in the settings of an already built wall does not work.
![image](https://github.com/aki-art/ONI-Mods/assets/50534207/d139ac75-57ab-45b9-8b73-f27248bf8ea4)

Attached my translation file, maybe I did something wrong and that's why the translation doesn't work. In the "DESCRIPTION" string, I just copied the text from the "EFFECT" string. I couldn't come up with a description.
[ru.zip](https://github.com/aki-art/ONI-Mods/files/12224084/ru.zip)

I'm a little confused about how Copy Pattern and Copy Color works, maybe I'm just dumb)

Is it possible to make a custom wall without a border? Maybe I just don't know how.  I would like to see borders like drywall or without. 
![image](https://github.com/aki-art/ONI-Mods/assets/50534207/35ade028-d3a6-4c42-836a-fcde35e1bf70)

My understanding is that there will be no border only if you use the same wall texture. Is it possible to make a mode or option without border? I apologize for this picture, I didn't have another example.
![image](https://github.com/aki-art/ONI-Mods/assets/50534207/00640465-c35c-4e6d-8795-d08069349901)

[Player.log](https://github.com/aki-art/ONI-Mods/files/12224297/Player.log)

**Comment by aki-art** [comment]
You can now set a BorderTag on the tiles, see the new puft wallpaper example.

In future, please :
- Do not post hentai on my git, wtf
- Post separate issues for separate issues (translation and borders)
- do not mark feature requests as bugs.

**Comment by DarkEviL88** [comment]
I'm sorry. I didn't mark the request as a bug why the bug tag was added I don't understand, I was just writing text and attaching files, maybe I don't fully understand how to use github.
