### ISSUE TITLE
Bio-Inks: Rechargeable Printing Pod

### ISSUE THREAD

**Issue by spaelling** [aki-art/ONI-Mods#56]
**Describe the bug**
Crash when starting the game

**Problem mod**  
- Bio-Inks: Rechargeable Printing Pod

**To Reproduce**
Crashes on startup of game

**Expected behavior**

**Log**

[Player.log](https://github.com/aki-art/ONI-Mods/files/12472869/Player.log)

**Comment by aki-art** [comment]
Should be fixed in newest update, live on steam
