### ISSUE TITLE
True Tiles crashes with the newer updates.

### ISSUE THREAD

**Issue by lidlesslenz** [aki-art/ONI-Mods#60]
Enabling the mod and starting a save crashes the game.

1. Enable True Tiles
2. Load colony.
3. Crash.

[Player.log](https://github.com/aki-art/ONI-Mods/files/12837854/Player.log)

Also it crashed with Bio-Inks and Mod Manager (by Ony), if enabled together.

**Comment by aki-art** [comment]
You have an outdated version of my mod. 
Please try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283)
