### ISSUE TITLE
Bio-Inks: Rechargeable Printing Pod Crash

### ISSUE THREAD

**Issue by Nebelun** [aki-art/ONI-Mods#62]
**Describe the bug**
I just started modding oxygen included so this is my first go at installing the mod. After clicking the button in the replicator menu to get bio-ink the game crashes

**Problem mod**  
- Bio-inks

**To Reproduce**
1. Wait for replicator to activate
2. Click "Deliver Bio-Ink Button"
3. Crash...

**Expected behavior**
The game to not crash.

**Log**

https://pastebin.com/sNQDWCkV

**OS**
[Windows/Linux/iOS]
Windows 10

**Comment by aki-art** [comment]
Fixed in v1.5.4, please try updating the mod.
