### ISSUE TITLE
Spooky Pumpkin Costume Causes Game to Crash

### ISSUE THREAD

**Issue by Machu92** [aki-art/ONI-Mods#64]
**Describe the bug**
Basically I have a ~900 cycle save that uses this mod along with dozens of others and starting today the game has started crashing. When I disable the mod the game crashes completely but when I enable the mod the game takes me to a crash report screen and says that Spooky Pumpkin is the problem mod. I played the game last night and it was working alright, but I think the issue has something to do with the costumes as part of the Spooky Pumpkin mod since the crash reports mention something about face paint and I only started using any of the costumes last night. Specifically Ashkan has a scarecrow costume and Lindsay has a different costume too.

**Problem mod**  
- Spooky Pumpkin

**To Reproduce**
1. Start Game
2. Load colony
3. Crash

**Expected behavior**

**Log**
[Player.log](https://github.com/aki-art/ONI-Mods/files/13508240/Player.log)
[ONI Crash Report.txt](https://github.com/aki-art/ONI-Mods/files/13508252/ONI.Crash.Report.txt)

**OS**
Windows

**Additional context**
If I open up a new save file all of the mods work correctly, and if I go back to a cycle before I had them put on the costumes it loads correctly. I'm able to go about 8 cycles back before I last saved without it crashing so I should be ok to play, but I thought you should know about this bug.

**Comment by aki-art** [comment]
Please attach a log from the time the game crashed. You seem to have restarted the game since, the mod isn't even enabled in this log.

**Comment by Machu92** [comment]
You're right, I saw the log with the error at one point but then made this post and sent the file after I had already gotten the game fixed by mistake, I don't know much about coding. Also I'm sorry but I've tried for like an hour at this point to replicate the error to get a proper error log but it's not showing up anymore so I guess it resolved itself.
