### ISSUE TITLE
[Bio-Inks] Using a care package ink doesn't fill all slots with care packages

### ISSUE THREAD

**Issue by LakeQueen** [aki-art/ONI-Mods#68]
**Describe the bug**
Using a nutritious bio ink printed 1 food item and 3 duplicants. Using a seeded bio ink printed 1-2 seed items and more duplicants.

**Problem mod**  
- Bio-Inks (default settings)
- Other printing pod mods: DGSM (starting dupes only, disabled in-game), [Synchronised Telepad](https://steamcommunity.com/sharedfiles/filedetails/?id=2686262124)

**To Reproduce**
1. Use a care package ink.

**Expected behavior**
Using a care package ink should only print care packages of that type, as shown on the mod page's gallery.

**Log**
N/A

**OS**
Windows 11

**Additional context**
![image](https://github.com/aki-art/ONI-Mods/assets/40394423/82e373d0-6617-4ef5-8e30-eb56d4840d55)

**Comment by Sgt-Imalas** [comment]
if dgsm is enabled while playing, it will still affect the printing pod (even if you turned editing off).
dgsm does not respect other mods, so it will override the inks printing pod.

**Comment by aki-art** [comment]
Unfortunately i would need to patch Ony's mod to fix this, essentially modding her mod. I have asked for her permission for this about a year ago but was denied, there is nothing else i can do :(
