### ISSUE TITLE
[Aki's Extra Twitch Events]: Game crash when i load colony

### ISSUE THREAD

**Issue by WLAN57** [aki-art/ONI-Mods#73]
### What happened?

When I load the colony with this mod the game crashes. If this mod off, everything runs normally.

### Mod Version

Last

### Operating System

Windows

### Which mod did this happen with?

Extra Twitch Events

### Which branch are you on

Default

### Log

https://pastebin.com/Q5b3nZnX

### Local Install

- [ ] Local

**Comment by aki-art** [comment]
I will not be able to fix this mod until the base mod, Twitch Integration, is updated.
