### ISSUE TITLE
[Bio-Inks]: Crashes when loading save.

### ISSUE THREAD

**Issue by 6135** [aki-art/ONI-Mods#74]
### What happened?

Mod causes game to crash to desktop without error screen when enabled.

### Operating System

Windows

### Which mod did this happen with?

Bio-Inks

### Which branch are you on

Default

### Log

[Player.log](https://github.com/user-attachments/files/16321353/Player.log)

### Local Install

- [ ] Local

**Comment by aki-art** [comment]
1. Your steam mods are failing to update. It should be trying to telling you in a dialog, in an infinite "STEAM DOWNLOAD FAILED" loop.
- Close Steam (entirely quit the steam client and the game)
- Delete this file (make a backup first): `E:/GamesSteam/steamapps/workshop/appworkshop_457140.acf`
- Try starting the game now.

If that didn't work, temporarily disable Mod Manager, and try using [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283), which besides updating also contains an attempted fix for this specific issue. (You can resume to using Mod Manager after)

If your mods cannot update after either solution, report the update failure to [Klei bug tracker. ](https://forums.kleientertainment.com/klei-bug-tracker/oni/)

2. If the crash still happens even after the mods successfully updated, please send me another log, but this time from `E:/GamesSteam/steamapps/common/OxygenNotIncluded`, the latest SimDLL_CRASH_release. This is a unique crash dump for sim crashes and may contain further clues.

**Comment by 6135** [comment]
Alright I'll follow up next Saturday. Currently on holiday.
