### ISSUE TITLE
Bio-Inks: Rechargeable Printing Pod

### ISSUE THREAD

**Issue by Yoshitaka-Kogirey** [aki-art/ONI-Mods#78]
### What happened?

![3HbKlqrSe4A](https://github.com/user-attachments/assets/0c9c4d8d-d339-4f6d-b6ab-eaca66eb7da5)

### Mod Version

1.5.6.0

### Operating System

Windows

### Which mod did this happen with?

Bio-Inks

### Which branch are you on

Default

### Log

[Player.log](https://github.com/user-attachments/files/16364312/Player.log)

### Local Install

- [ ] Local

**Comment by Nygmus** [comment]
https://pastebin.com/i9ZWxrP0

Crashes upon accessing printing pod.

**Comment by aki-art** [comment]
Should be fixed now, use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) if the game refuses to install the update.
