### ISSUE TITLE
Golden Throne: Toilet not making any sounds

### ISSUE THREAD

**Issue by Nick56731** [aki-art/ONI-Mods#79]
### What happened?

title (look/hear the video)

https://github.com/user-attachments/assets/391af5cf-8797-4a9f-90a2-54ebe934c6de

### Mod Version

1.2

### Operating System

Windows

### Which mod did this happen with?

The Golden Throne

### Which branch are you on

Default

### Log

[Player.log](https://github.com/user-attachments/files/16380712/Player.log)

### Local Install

- [ ] Local

**Comment by aki-art** [comment]
Should be fixed in newest version. if you still have issues let me know.
