### ISSUE TITLE
[Mod Name]:Bio-Inks: Rechargeable Printing Pod

### ISSUE THREAD

**Issue by lun4rite** [aki-art/ONI-Mods#82]
### What happened?

I know you get other logs saying game crashes on random dupe sry 

 I tried deleting Documents\Klei\OxygenNotIncluded\mods\config\PrintingPodRecharge\settings.json and game still crashes with both random dupe chance %100 and suspicious ink uninstalling and reinstalling doesn't work aswell also if it's related I have a dupe with vaccilinator perk 

I have no clue what to do so pls help

Also: I love your mods man you are the best :3 :

### Mod Version

1.5.6

### Operating System

Windows

### Which mod did this happen with?

Bio-Inks

### Which branch are you on

Default

### Log

[Player.log](https://github.com/user-attachments/files/16476977/Player.log)

### Local Install

- [ ] Local

**Comment by clayharris** [comment]
Same here on random dupe.
In my Player.log I'm seeing (among a TOOOON of IsContentActive warnings)
 

> [11:47:37.689] [1] [WARNING] A mod is calling IsContentActive which is obsolete and needs to be fixed.
> [11:47:37.689] [1] [WARNING] A mod is calling IsContentActive which is obsolete and needs to be fixed.
> [11:47:37.689] [1] [WARNING] A mod is calling IsContentActive which is obsolete and needs to be fixed.
> [11:47:37.689] [1] [ERROR] IsContentActive was called with a newer DLC which is not allowed.
> [11:47:37.707] [1] [INFO] Bio-Inks: Rechargeable Printing Pods's assembly declared the method PrintingPodRecharge.DupeGenHelper:IsTraitInvalid in the stack trace, adding to referenced mods list
> IsContentActive was called with a newer DLC which is not allowed.
> [11:47:37.722] [1] [WARNING] A mod is calling IsContentActive which is obsolete and needs to be fixed.
> [11:47:37.722] [1] [WARNING] A mod is calling IsContentActive which is obsolete and needs to be fixed.

**Comment by aki-art** [comment]
Should be fixed now, use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) if the game refuses to install the update.
