### ISSUE TITLE
[Plastic Door]: Add config option to disable gas mixing

### ISSUE THREAD

**Issue by nedart** [aki-art/ONI-Mods#83]
### What happened?

I'd love it if this mod had the option to prevent gases from mixing even when dupes walk through the door. I realize it's overpowered, I've been playing with the self-sealing airlocks mod since forever and this mod seems a good way to make that slightly more balanced.

Apologies if this is wrongly labeled, I can't find a button to change this to a feature request. I was directed here to suggest changes. 

### Operating System

Windows

### Which mod did this happen with?

Plastic Door

### Which branch are you on

Default

### Log

N/A

### Local Install

- [ ] Local

**Comment by aki-art** [comment]
Plastic Door is Romens mod, I'm only the artist, please redirect your issue to him.
