### ISSUE TITLE
Gravitas Shipping Container: QoL update broke the mod

### ISSUE THREAD

**Issue by ManInTheMists** [aki-art/ONI-Mods#88]
### What happened?

Crash when starting ONI with this mod installed and active.

### Operating System

Windows

### Which mod did this happen with?

Gravitas Shipping Container

### Which branch are you on

Default

### Log

[Player.log](https://github.com/user-attachments/files/17853054/Player.log)

### Local Install

- [ ] Local

**Comment by aki-art** [comment]
Fixed and live on Workshop. If you don't see an update please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
